# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Draguve'
description: 'Draguve'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"
email: 'draguve@gmail.com'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  Landing: /landing/

# Footer nav
navigation_footer:
  Back to top: "#top"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/draguve
  GitHub: https://github.com/draguve

navigation_footer:
  Created by Draguve: https://github.com/draguve

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

twitter:
  username: 'draguve'

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  Reddit: "#FF4500"
  Email: "#3B5998"

footer_icons:
  twitter: "https://twitter.com/draguve"
  github: "https://github.com/draguve"
  instagram: "https://www.instagram.com/draguve/"
  
keep_files: [assets/js/jarallax.min.js]

